plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.137'
    id 'me.modmuss50.mod-publish-plugin' version '2.2.0'
}

version = project.version
group = project.group

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }

    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = "NeoForge"
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "CreateMod"
                url = "https://maven.createmod.net"
            }
        }
        filter {
            includeGroup "com.simibubi.create"
            includeGroup "net.createmod.ponder"
            includeGroup "dev.engine-room.flywheel"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Registrate"
                url = "https://maven.ithundxr.dev/snapshots"
            }
        }
        filter {
            includeGroup "com.tterrag.registrate"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "BlameJared"
                url = "https://maven.blamejared.com"
            }
        }
        filter {
            includeGroup "mezz.jei"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "TeamAbnormals"
                url = "https://maven.teamabnormals.com/"
            }
        }
        filter {
            includeGroup "com.teamabnormals"
        }
    }
}

neoForge {
    version = neoforge_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()}"
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // YACL
    implementation "maven.modrinth:yacl:${yacl_version}-neoforge"

    // EMI
    runtimeOnly "maven.modrinth:emi:1.1.22+1.21.1+neoforge"

    // Raised
    compileOnly "maven.modrinth:raised:NeoForge-${raised_version}"
    runtimeOnly "maven.modrinth:raised:NeoForge-${raised_version}"

    // Farmer's Delight
    compileOnly "maven.modrinth:farmers-delight:1.21.1-1.3.2"
    runtimeOnly "maven.modrinth:farmers-delight:1.21.1-1.3.2"

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.6'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'                      : version,
            'group'                        : project.group,
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'license'                      : license,
            'description'                  : project.description,
            'neoforge_version'             : neoforge_version,
            'neoforge_loader_version_range': neoforge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version,
            'yacl_version'                 : yacl_version,
    ]

    filesMatching(['pack.mcmeta', 'META-INF/neoforge.mods.toml', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
    changelog = rootProject.file("CHANGELOG-LATEST.md").text
    type = STABLE
    version = "${project.version}-${minecraft_version}"
    displayName = "${mod_name} ${minecraft_version} - ${project.version}"
    modLoaders.add('neoforge')

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = ""
        minecraftVersions.add("${minecraft_version}")
        client = true
        server = true

        requires("yacl")
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "kCbtgaek"
        minecraftVersions.add("${minecraft_version}")

        requires("yacl")
    }
}
